name: JH Repository Autoupdate

on:
  schedule:
    - cron:  '30 2 * * *'
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare repository
    runs-on: [self-hosted]
    if: ${{ github.repository_owner == 'jethubjhaos' }}
    steps:
      - name: Clean git
        run: |
          mkdir -p rebase_wheels
          cd rebase_wheels
          git remote remove upstream || true
      - name: Checkout jethub wheels repository (master)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: jethubjhaos/wheels
          path: rebase_wheels
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
      - name: Rebase wheels repository (master)
        run: |
          cd rebase_wheels
          UPSTREAM=https://github.com/home-assistant/wheels.git
          git remote add upstream $UPSTREAM  || true
          git fetch upstream master
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name  "GitHub Actions"
          git rebase upstream/master
          if [ "$(git status | grep diverged)" ]; then
            git push origin $(git branch --show-current) --force-with-lease;
          else
            git push origin $(git branch --show-current)
          fi;
          git remote remove upstream || true

      - name: Checkout jethub wheels repository (master-jethub)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: jethubjhaos/wheels
          path: rebase_wheels
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master-jethub
      - name: Rebase wheels repository (master-jethub)
        run: |
          cd rebase_wheels
          git pull
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name  "GitHub Actions"
          git rebase origin/master
          if [ "$(git status | grep diverged)" ]; then
            git push origin $(git branch --show-current) --force-with-lease;
          else
            git push origin $(git branch --show-current)
          fi;
